### ISSUE TITLE
Collision Generation not working in Godot 4.3?

### ISSUE THREAD

**Issue by julia-maliauka** [SanjoSolutions/tileset-collision-generator-free-version#1]
Hello! I'm not sure if this is user error, but I tried to follow the instructions specified in the plugin's page here - https://sanjox.itch.io/godot-collision-generator - and also the instructions from this page: https://godotengine.org/asset-library/asset/3121

I have the paid version of the plugin, do you know if it works for 4.3? I tried a few different tilesets, and it just did not do anything at all, without any error messages. 

The reason I bought the paid version was because I got an error message saying my tiles were larger than 240 px, which was not the case for my tileset, so maybe that's a hint?

**Comment by SanjoSolutions** [comment]
Ok, I will check it out.

**Comment by SanjoSolutions** [comment]
I had tested it with 4.2.2 in the past.

**Comment by SanjoSolutions** [comment]
I have released fixes for 4.3. The paid version is already up on itch.io. The free version can be directly downloaded from this repo. It's still in review on the Godot Asset Library.

**Comment by julia-maliauka** [comment]
Thank you so much!
